import { PurchaseOrder, Supplier, ProcurementStats } from './types';

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-2026-001',
    supplier: 'SteelMax Industries',
    status: 'APPROVED',
    items: [
      { id: 'item-001', name: 'Steel Beams', description: 'H-Beam 200x200mm', quantity: 50, unit: 'pcs', unitPrice: 8500, total: 425000 },
      { id: 'item-002', name: 'Rebar', description: '16mm diameter', quantity: 200, unit: 'pcs', unitPrice: 450, total: 90000 },
    ],
    subtotal: 515000,
    tax: 61800,
    total: 576800,
    orderDate: '2026-04-20',
    deliveryDate: '2026-04-27',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    requestedBy: 'Kyle Arrieta',
    approvedBy: 'Elaine Aguilar',
  },
  {
    id: 'po-002',
    poNumber: 'PO-2026-002',
    supplier: 'Concretia Supplies',
    status: 'PENDING',
    items: [
      { id: 'item-003', name: 'Ready Mix Concrete', description: 'Grade 30', quantity: 100, unit: 'cu.m', unitPrice: 3200, total: 320000 },
    ],
    subtotal: 320000,
    tax: 38400,
    total: 358400,
    orderDate: '2026-04-19',
    deliveryDate: '2026-04-26',
    projectId: 'proj-002',
    projectName: 'Cebu Commercial Complex',
    requestedBy: 'Gin Tyrone Aguino',
  },
  {
    id: 'po-003',
    poNumber: 'PO-2026-003',
    supplier: 'EquipRent Philippines',
    status: 'ORDERED',
    items: [
      { id: 'item-004', name: 'Tower Crane Rental', description: '50-ton capacity', quantity: 2, unit: 'weeks', unitPrice: 14000, total: 28000 },
    ],
    subtotal: 28000,
    tax: 3360,
    total: 31360,
    orderDate: '2026-04-18',
    deliveryDate: '2026-04-21',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    requestedBy: 'Santi Abubo',
    approvedBy: 'Admin Super',
  },
  {
    id: 'po-004',
    poNumber: 'PO-2026-004',
    supplier: 'BuildRight Hardware',
    status: 'RECEIVED',
    items: [
      { id: 'item-005', name: 'Safety Helmets', description: 'Yellow, ABS', quantity: 100, unit: 'pcs', unitPrice: 350, total: 35000 },
      { id: 'item-006', name: 'Safety Vest', description: 'Reflective, Orange', quantity: 100, unit: 'pcs', unitPrice: 180, total: 18000 },
    ],
    subtotal: 53000,
    tax: 6360,
    total: 59360,
    orderDate: '2026-04-15',
    deliveryDate: '2026-04-17',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    requestedBy: 'Marc Justin Arzadan',
    approvedBy: 'Elaine Aguilar',
  },
  {
    id: 'po-005',
    poNumber: 'PO-2026-005',
    supplier: 'PlumbMaster Pro',
    status: 'DRAFT',
    items: [
      { id: 'item-007', name: 'PVC Pipes', description: '4-inch diameter', quantity: 200, unit: 'pcs', unitPrice: 450, total: 90000 },
      { id: 'item-008', name: 'Pipe Fittings', description: 'Assorted sizes', quantity: 500, unit: 'pcs', unitPrice: 85, total: 42500 },
    ],
    subtotal: 132500,
    tax: 15900,
    total: 148400,
    orderDate: '2026-04-20',
    projectId: 'proj-003',
    projectName: 'Davao Residential Estate',
    requestedBy: 'Marlon Aguilar',
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'SteelMax Industries',
    contact: 'John Smith',
    email: 'sales@steelmax.com',
    phone: '+63 2 8888 1111',
    address: 'Makati City, Metro Manila',
    category: 'Steel & Metal',
    rating: 4.8,
    status: 'ACTIVE',
  },
  {
    id: 'sup-002',
    name: 'Concretia Supplies',
    contact: 'Maria Garcia',
    email: 'orders@concretia.ph',
    phone: '+63 2 8777 2222',
    address: 'Quezon City, Metro Manila',
    category: 'Concrete',
    rating: 4.5,
    status: 'ACTIVE',
  },
  {
    id: 'sup-003',
    name: 'EquipRent Philippines',
    contact: 'Robert Chen',
    email: 'rentals@equiprent.ph',
    phone: '+63 2 8666 3333',
    address: 'Pasig City, Metro Manila',
    category: 'Equipment Rental',
    rating: 4.2,
    status: 'ACTIVE',
  },
  {
    id: 'sup-004',
    name: 'BuildRight Hardware',
    contact: 'Sarah Lee',
    email: 'sales@buildright.ph',
    phone: '+63 2 8555 4444',
    address: 'Taguig City, Metro Manila',
    category: 'Safety Equipment',
    rating: 4.6,
    status: 'ACTIVE',
  },
  {
    id: 'sup-005',
    name: 'PlumbMaster Pro',
    contact: 'Mike Johnson',
    email: 'orders@plumbmaster.ph',
    phone: '+63 2 8444 5555',
    address: 'Mandaluyong City, Metro Manila',
    category: 'Plumbing',
    rating: 4.3,
    status: 'INACTIVE',
  },
];

export const procurementStats: ProcurementStats = {
  totalOrders: 24,
  pendingApproval: 3,
  totalSpent: 1250000,
  activeSuppliers: 12,
};

export const statusColors: Record<string, { bg: string; text: string }> = {
  DRAFT: { bg: 'bg-gray-400/10', text: 'text-gray-400' },
  PENDING: { bg: 'bg-yellow-400/10', text: 'text-yellow-400' },
  APPROVED: { bg: 'bg-green-400/10', text: 'text-green-400' },
  ORDERED: { bg: 'bg-blue-400/10', text: 'text-blue-400' },
  RECEIVED: { bg: 'bg-purple-400/10', text: 'text-purple-400' },
  CANCELLED: { bg: 'bg-red-400/10', text: 'text-red-400' },
};
