import { Document, DocumentCategory } from './types';

export const mockDocuments: Document[] = [
  {
    id: 'doc-001',
    name: 'Manila Tower Construction Contract.pdf',
    type: 'PDF',
    category: 'CONTRACT',
    size: '2.4 MB',
    uploadedBy: 'Admin Super',
    uploadedAt: '2026-04-20T10:30:00Z',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-002',
    name: 'April 2026 Payroll Summary.xlsx',
    type: 'XLS',
    category: 'REPORT',
    size: '856 KB',
    uploadedBy: 'Elaine Aguilar',
    uploadedAt: '2026-04-19T14:00:00Z',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-003',
    name: 'Cesar Abubo - March 2026 Payslip.pdf',
    type: 'PDF',
    category: 'PAYSLIP',
    size: '124 KB',
    uploadedBy: 'System',
    uploadedAt: '2026-04-15T09:00:00Z',
    employeeId: 'E0002',
    employeeName: 'Cesar Abubo',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-004',
    name: 'Building Permit - Cebu Complex.pdf',
    type: 'PDF',
    category: 'PERMIT',
    size: '3.1 MB',
    uploadedBy: 'Marc Justin Arzadan',
    uploadedAt: '2026-04-18T11:30:00Z',
    projectId: 'proj-002',
    projectName: 'Cebu Commercial Complex',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-005',
    name: 'Invoice INV-2026-001 - Milestone 3.pdf',
    type: 'PDF',
    category: 'INVOICE',
    size: '180 KB',
    uploadedBy: 'Elaine Aguilar',
    uploadedAt: '2026-04-20T09:15:00Z',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-006',
    name: 'Q1 2026 Financial Report.pdf',
    type: 'PDF',
    category: 'REPORT',
    size: '1.8 MB',
    uploadedBy: 'Admin Super',
    uploadedAt: '2026-04-10T16:00:00Z',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-007',
    name: 'Site Inspection Report - Week 15.docx',
    type: 'DOC',
    category: 'REPORT',
    size: '425 KB',
    uploadedBy: 'Kyle Arrieta',
    uploadedAt: '2026-04-17T13:00:00Z',
    projectId: 'proj-001',
    projectName: 'Manila Tower Construction',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-008',
    name: 'Material Delivery Receipt.jpg',
    type: 'IMG',
    category: 'OTHER',
    size: '2.1 MB',
    uploadedBy: 'Gin Tyrone Aguino',
    uploadedAt: '2026-04-19T08:30:00Z',
    projectId: 'proj-002',
    projectName: 'Cebu Commercial Complex',
    url: '#',
    isArchived: false,
  },
  {
    id: 'doc-009',
    name: 'Employee Handbook 2026.pdf',
    type: 'PDF',
    category: 'OTHER',
    size: '5.2 MB',
    uploadedBy: 'Admin Super',
    uploadedAt: '2026-01-15T10:00:00Z',
    url: '#',
    isArchived: true,
  },
  {
    id: 'doc-010',
    name: 'Leave Application - Marlon Aguilar.pdf',
    type: 'PDF',
    category: 'OTHER',
    size: '95 KB',
    uploadedBy: 'Marlon Aguilar',
    uploadedAt: '2026-04-16T11:00:00Z',
    employeeId: 'E0003',
    employeeName: 'Marlon Aguilar',
    url: '#',
    isArchived: false,
  },
];

export const documentCategories: DocumentCategory[] = [
  { id: 'ALL', name: 'All Documents', count: 10, icon: 'Folder', color: '#facc15' },
  { id: 'CONTRACT', name: 'Contracts', count: 1, icon: 'FileText', color: '#3b82f6' },
  { id: 'INVOICE', name: 'Invoices', count: 1, icon: 'Receipt', color: '#22c55e' },
  { id: 'REPORT', name: 'Reports', count: 3, icon: 'BarChart', color: '#8b5cf6' },
  { id: 'PAYSLIP', name: 'Payslips', count: 1, icon: 'DollarSign', color: '#f97316' },
  { id: 'PERMIT', name: 'Permits', count: 1, icon: 'Shield', color: '#06b6d4' },
  { id: 'OTHER', name: 'Others', count: 3, icon: 'File', color: '#6b7280' },
];

export const typeIcons: Record<string, string> = {
  PDF: '📄',
  DOC: '📝',
  XLS: '📊',
  IMG: '🖼️',
  OTHER: '📁',
};

export const typeColors: Record<string, string> = {
  PDF: 'bg-red-400/10 text-red-400',
  DOC: 'bg-blue-400/10 text-blue-400',
  XLS: 'bg-green-400/10 text-green-400',
  IMG: 'bg-purple-400/10 text-purple-400',
  OTHER: 'bg-gray-400/10 text-gray-400',
};
